import { Storyline } from './storyline.model';

export const STORYLINE: Storyline[] = [
  new Storyline('The neatly trimmed lawn leading up to the cute red house with the white trim has only a few leaves cluttering the grass, but there do not appear to be any pumpkins on the white porch. As you approach, you realize that there are no lights on in the house interior.', [], 1),
  new Storyline('You walk up the pathway past a dilapitated basketball hoop. A tricycle and some worn looking toys are scattered next to the door. You can smell hot apple cider and hear the excited sound of voices as you stand on the porch.', ['candy corn', 'caramel apple', 'candy cigarette', 'black licorice', 'candy pumpkin', 'candy cigarette'], 2),
  new Storyline('The large white house glows in the faint light. As you walk up the rosebush lined walkway, you can see large pumpkins carved to have huge toothy grins decorating the expansive wrap-around porch.', ['dental floss'], 3),
  new Storyline('You approach the large multilevel brown house and can hear the noise of music and laughter from street. As you near the door, three dark figures wearing horrific hairy masks lunge out of the darkness howling. You drop your candy bucket, out of which half your candy spills. Too scared to pick up the spilled treasure, you grab your bucket and run.', [ ], 4),
  new Storyline('The lovely tudor brick house on the end of the block is one of your favorites. You can see a dignified black cat sitting in the window looking out at you. The light from the ornately carved pumpkins give the house a cheerful and promising effect.', ['candy corn', 'caramel apple', 'candy cigarette', 'black licorice', 'candy pumpkin', 'black licorice'], 5),
  new Storyline('This is the house of your school friend, Beth. You can see the blue of her her bedroom through the upstairs window and the thick vines that grow up the lattice on the East side. Colorful banners in Halloween colors bedeck the front walkway and crowds of kids are lined up to ring the doorbell.', ['candy corn', 'caramel apple', 'candy cigarette', 'black licorice', 'candy pumpkin', 'candy corn'], 6),
  new Storyline('The tiny house with blue trim sits back from the street between two towering maple trees. You can spot the dark outline of an owl high in the branches, which will explains all the hooting. Decorative spiderwebs are strung from the lowest branches framing a basketball-sized paper-mache spider.', ['candy corn', 'caramel apple', 'candy cigarette', 'black licorice', 'candy pumpkin', 'caramel apple'], 7),
  new Storyline('Walking toward the gaudily painted house, you glance around the overgrown grass of the yard looking for the source of the skunk smell. A VW Bus with handdrawn flowers speckling its doors sits in the driveway. On the pine needle strewn porch, you see a large pottery bowl filled with candy and a sign that reads "Please take one."', [], 8),
  new Storyline('You jerk open the rusted gate at the front of the abandoned Frieberg place. The once majestic home of the late doctor has fallen into disrepair. Rumor is that his grandchildren have inherited the place, but no one has met them in the neighborhood. Clearly they do not invest their time in house upkeep.', [], 9),
  new Storyline('Just beyond the cast-iron gate, you walk past an elaborate paper-mache cemetary with jaunty skeletons suspended from the trees. You can just make out the "Monster Mash" being broadcast from within the party house. Through the large front window, you see adults in costumes bobbing for apples awkwardly.', ['candy corn', 'caramel apple', 'candy cigarette', 'black licorice', 'candy pumpkin', 'candy pumpkin'], 10),              
];
